[package]
name = "rust_crawler"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = { version = "0.13", features = ["json"] }
tokio = { version = "1", features = ["full"] }
scraper ={ version = "0.25.0"}
rand = "0.8"
futures = "0.3"
chrono = "0.4"